[build]
  publish = "dist"
  command = "yarn build"

[environment]
  FB_API_KEY = "PROD_FB_API_KEY"
  FB_AUTH_DOMAIN = "PROD_FB_AUTH_DOMAIN"
  FB_DB_URL = "PROD_FB_DB_URL"
  FB_PROJECT_ID = "PROD_FB_PROJECT_ID"
  FB_STORAGE_BUCKET = "PROD_FB_STORAGE_BUCKET"
  FB_MSG_SENDER_ID = "PROD_FB_MSG_SENDER_ID"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
